
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-muted/40 flex items-center justify-center p-4">
      <Card className="w-full max-w-4xl">
        <CardHeader>
          <CardTitle className="text-3xl">Terms of Service</CardTitle>
          <p className="text-muted-foreground">Last Updated: {new Date().toLocaleDateString()}</p>
        </CardHeader>
        <CardContent className="prose dark:prose-invert max-w-none">
          <h2>1. Introduction</h2>
          <p>
            Welcome to vaselearn (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). These Terms of Service govern your use of our application and provide information about the vaselearn Service, outlined below. When you create a vaselearn account or use vaselearn, you agree to these terms.
          </p>
          
          <h2>2. The vaselearn Service</h2>
          <p>
            We agree to provide you with the vaselearn Service. The Service includes all of the vaselearn products, features, applications, services, technologies, and software that we provide to advance vaselearn's mission: To help you learn and grow more effectively.
          </p>

          <h2>3. Your Commitments</h2>
          <p>
            In return for our commitment to provide the Service, we require you to make the below commitments to us.
          </p>
          <ul>
            <li>You must be at least 13 years old.</li>
            <li>You must not be prohibited from receiving any aspect of our Service under applicable laws.</li>
            <li>You must not use the service for any illegal or unauthorized purpose.</li>
          </ul>

          <h2>4. Content and Ownership</h2>
          <p>
            You own the content you create and store on vaselearn. We do not claim ownership of your notes, goals, or other data you provide. However, by using the service, you grant us a license to use the content generated by you to operate, develop, and improve our services.
          </p>
          <p>
            AI-generated content, such as quiz questions, is provided for your use within the service. We do not guarantee the accuracy of AI-generated content.
          </p>

          <h2>5. Disclaimer of Warranties</h2>
          <p>
            The Service is provided &quot;as is,&quot; and we cannot guarantee it will be safe and secure or will work perfectly all the time. TO THE EXTENT PERMITTED BY LAW, WE ALSO DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
          </p>

          <h2>6. Limitation of Liability</h2>
          <p>
            Our liability shall be limited to the fullest extent permitted by applicable law, and under no circumstance will we be liable to you for any lost profits, revenues, information, or data, or consequential, special, indirect, exemplary, punitive, or incidental damages arising out of or related to these Terms or the vaselearn Products.
          </p>

          <hr />
          <p className="text-center">
            <Link href="/login" className="text-primary hover:underline">Back to App</Link>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
