name: Next.js Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Set environment variables (optional)
      - name: Set Firebase and Model Env Vars
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_HF_MODEL_URL=${{ secrets.NEXT_PUBLIC_HF_MODEL_URL }}" >> $GITHUB_ENV

      # 5. Build the app (no export)
      - name: Build Next.js App
        run: |
          npm run build

      # 6. (Optional) Run tests
      - name: Run tests
        run: npm run test || echo "No tests configured"

      # 7. (Optional) Upload build output as artifact (useful for debugging)
      - name: Upload .next build output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: .next
